---
- name: Install pam_ssh_agent_auth for {{ ansible_os_family }}
  ansible.builtin.include_tasks: {{ ansible_os_family | lower }}.yml

- name: Add sudoers ssh_auth_sock
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ssh_auth_sock
    src: files/sudo_ssh_auth_sock
    mode: '0640'
    owner: root
    group: root

- name: Add authorized keys
  ansible.posix.authorized_key:
    path: /etc/security/authorized_keys
    user: root
    key: "{{ item }}"
  with_items:
    - "{{ authorized_keys }}"
